USE JUNE13TH;







CREATE TABLE CUSTOMERTB(
	C_ID INT IDENTITY(1,1) PRIMARY KEY,
	C_NAME VARCHAR(255) NOT NULL,
	C_ADDRESS VARCHAR(255),
	EMAIL VARCHAR(255)  NOT NULL UNIQUE


);






INSERT INTO CUSTOMERTB
VALUES('NIRJON','DHAKA IEHRKDDF','hEgsdgHHFT@gma4il.com','FGFG');


CREATE TABLE ORDERTB(
	O_ID INT IDENTITY(1,1) PRIMARY KEY,
	C_ID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMERTB(C_ID),

);



INSERT INTO ORDERTB
VALUES(3);


CREATE TABLE PRODUCTTB(
	PRODUCT_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL

);


ALTER TABLE ORDERTB ADD PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCTTB(PRODUCT_ID); ; -- ADD FOREIGN KEY



ALTER TABLE CUSTOMERTB ADD COUNTRY VARCHAR(255) NULL DEFAULT 'Bangladesh'; --- HAS ERROR


--DML
UPDATE CUSTOMERTB SET C_NAME='GGGG' WHERE C_ID = 1 AND EMAIL ='hgsdg@gmail.com'; --ONLY UNIOQUE KEY IN WHERE

--DML DELETE
DELETE  FROM CUSTOMERTB WHERE C_ID = 3; --CAN'T DELETE RELATED ROW


--SELECT TABLES

SELECT * FROM PRODUCTTB;
SELECT * FROM ORDERTB;
SELECT * FROM CUSTOMERTB;
SELECT * FROM nirjon_demo;
